name: Pull Request Tests

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.8'
          - python-version: '3.9'
          - python-version: '3.10'
          - python-version: '3.11'

    steps:
    - uses: actions/checkout@v4

    # poetry has to be present to be used as a cache :/
    - run: pipx install poetry

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    
    - name: Check poetry.lock is up-to-date
      run: poetry check --lock

    - name: Install Dependencies
      run: poetry install --with dev

    - name: Run Tests
      run: poetry run pytest
