name: Release and Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write  # For PyPI trusted publishing
      contents: write  # For creating releases

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only dev

    - name: Python Semantic Release
      id: release
      run: poetry run semantic-release publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: release
    # Only run if a new release was created
    if: needs.release.outputs.released == 'true'
    runs-on: ubuntu-latest
    # Set up environment for PyPI Trusted Publisher
    environment:
      name: pypi
      url: https://pypi.org/p/rpi-hw-info
    
    # Enable PyPI Trusted Publisher via permissions
    permissions:
      contents: read
      id-token: write  # Required for PyPI's trusted publishing
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ needs.release.outputs.tag }}  # Checkout the tag created by semantic release
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    
    - name: Build
      run: |
        poetry build
    
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      # No more token needed - Trusted Publishers uses OIDC
